# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openjdk-17-jre wget
          version: 1.0

      # Runs a single command using the runners shell
      - name: Set up Creative
        run: |
          mkdir -p working/{creative,complete/creative}
          cd working/creative || exit

          mkdir -p assets/minecraft/{textures,models}
          rsync -a ../../merch/models/block assets/minecraft/models/block
          rsync -a ../../merch/textures/ assets/minecraft/textures
          cp ../../pack.mcmeta pack.mcmeta
          cp ../../pack.png pack.png

          zip -r creativepack.zip assets pack.mcmeta pack.png
          cd ../../
         
      - name: Set up Hub
        run: |
          mkdir -p working/{hub,complete/hub}
          cd working/hub || exit

          mkdir -p assets/minecraft/{textures,models}
          rsync -a ../../merch/models/block assets/minecraft/models/block
          rsync -a ../../merch/textures/ assets/minecraft/textures
          cp ../../pack.mcmeta pack.mcmeta
          cp ../../pack.png pack.png

          zip -r hubpack.zip assets pack.mcmeta pack.png
          cd ../../
    
      
      - name: Set up Resource Pack Converter
        run: |
          mv working/hub/hubpack.zip working/complete/hubpack.zip
          mv working/creative/creativepack.zip working/complete/creativepack.zip
          mkdir -p working/convert/template
          cp working/complete/*.zip working/convert/template
          wget https://jenkins.dc1.agentdid127.com/job/agentdid127/job/ResourcePackConverter/job/dev%252F1.21.4/lastSuccessfulBuild/artifact/Applications/Console/target/ResourcePackConverter-Console-2.2.5.jar
      
      - name: Convert to 1.21.4
        run: |
          cp -r working/convert/template working/convert/1_21_4
          cd working/convert/1_21_4/
          java -jar ../../../ResourcePackConverter-Console-*.jar --from 1.15.2 --to 1.21.4 --minify
          rm hubpack.zip
          rm creativepack.zip
          mv hubpack_converted.zip ../../complete/hubpack-1.21.4.zip
          mv creativepack_converted.zip ../../complete/creativepack-1.21.4.zip
          cd ../../../

      - name: Set up targets
        run: |
          mv working/complete .
          rm -rf working
          rm -f ResourcePackConverter-*.jar

          cd complete
          mkdir -p hubpack_1_21_4
          cd hubpack_1_21_4
          mv ../hubpack-1.21.4.zip .
          unzip hubpack-1.21.4.zip
          rm hubpack-1.21.4.zip
          cd ..

          mkdir -p creativepack_1_21_4
          cd creativepack_1_21_4
          mv ../creativepack-1.21.4.zip .
          unzip creativepack-1.21.4.zip
          rm creativepack-1.21.4.zip
          cd ..

          cd ..

          echo 'VERSION='$(cat version.txt) >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release Automatically Generated by software... Please change draft to add changelog.
          draft: true
          prerelease: false

      - name: Upload Hub Release
        id: upload-hub-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./complete/hubpack-1.21.4.zip
          asset_name: hubpack-1.21.4.zip
          asset_content_type: application/zip

      - name: Upload Creative Release
        id: upload-creative-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./complete/creativepack-1.21.4.zip
          asset_name: creativepack-1.21.4.zip
          asset_content_type: application/zip
