# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:g
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Creative
        run: |
          mkdir -p working/{creative,complete/creative}
          cd working/creative || exit

          mkdir -p assets/minecraft/{textures,models}
          rsync -a ../../merch/models/block assets/minecraft/models/block
          rsync -a ../../merch/textures/ assets/minecraft/textures
          cp ../../pack.mcmeta pack.mcmeta
          cp ../../pack.png pack.png

          zip -r creativepack.zip assets pack.mcmeta pack.png
          cd ../../
         
      - name: Set up Hub
        run: |
          mkdir -p working/{hub,complete/hub}
          cd working/hub || exit

          mkdir -p assets/minecraft/{textures,models}
          rsync -a ../../merch/models/block assets/minecraft/models/block
          rsync -a ../../merch/textures/ assets/minecraft/textures
          cp ../../pack.mcmeta pack.mcmeta
          cp ../../pack.png pack.png

          zip -r hubpack.zip assets pack.mcmeta pack.png
          cd ../../
    
      
      - name: Set up Resource Pack Converter
        run: |
          apt install openjdk-21-jre wget
          mv working/hub/hubpack.zip working/complete/hubpack.zip
          mv working/creative/creativepack.zip working/complete/creativepack.zip
          mkdir -p working/convert/template
          cp working/complete/*.zip working/convert/template
          wget https://jenkins.dc1.agentdid127.com/job/agentdid127/job/ResourcePackConverter/job/dev%252F1.21.4/lastSuccessfulBuild/artifact/Applications/Console/target/ResourcePackConverter-Console-2.2.5.jar
      
      - name: Convert to 1.21.4
        run: |
          cp -r working/convert/template working/convert/1_21_4
          cd working/convert/1_21_4/
          java -jar ../../../ResourcePackConverter-Console-*.jar --from 1.15.2 --to 1.21.4 --minify
          rm hubpack.zip
          rm creativepack.zip
          mv hubpack_converted.zip ../../complete/hubpack-1.21.4.zip
          mv creativepack_converted.zip ../../complete/creativepack-1.21.4.zip
          cd ../../../

      - name: Set up targets
        run: |
          mv working/complete .
          rm -rf working
          rm -f ResourcePackConverter-*.jar

          cd complete
          mkdir -p hubpack_1_21_4
          cd hubpack_1_21_4
          mv ../hubpack-1.21.4.zip .
          unzip hubpack-1.21.4.zip
          rm hubpack-1.21.4.zip
          cd ..

          mkdir -p creativepack_1_21_4
          cd creativepack_1_21_4
          mv ../creativepack-1.21.4.zip .
          unzip creativepack-1.21.4.zip
          rm creativepack-1.21.4.zip
          cd ..

          cd ..
      
      - uses: actions/upload-artifact@v4
        with:
         name: hubpack-1.21.4
         path: complete/hubpack_1_21_4
         retention-days: 90

      - uses: actions/upload-artifact@v4
        with:
         name: creativepack-1.21.4
         path: complete/creativepack_1_21_4
         retention-days: 90